[package]
name = "Companion Leveler"
description = "This MWSE mod allows both NPC and Creature companions to level up with the player based on their Class/Creature Type (Class Mode) or specific player selected build settings (Build Mode). Companions are also able to learn spells and abilities."
homepage = "https://www.nexusmods.com/morrowind/mods/51760"
repository = "https://github.com/Kleidium/companionLeveler"
authors = ["Kleidium"]
version = "3.3.0"

[tools.mwse]
lua-mod = "companionLeveler"
wait-until-initialize = true